"""
Key Derivation Functions for PQC-DLST-MQTT.

Core primitives:
  - SHAKE-256 (XOF) for channel key derivation (Phase I)
  - PRG (AES-CTR based, per Eq. 5) for sub-topic key derivation (Phase III)
  - SHAKE-256 for salt derivation and IV construction

Functions:
  - derive_channel_keys: Phase I — derive bidirectional channel keys from shared secret
  - derive_subtopic_key: Phase III — PRG-based per-sub-topic symmetric key (Eq. 5)
  - derive_salt:         Phase III — derive per-epoch salt from seed
"""

from Crypto.Hash import SHAKE256
from Crypto.Cipher import AES
import struct


def derive_channel_keys(shared_secret: bytes, nonce_client: bytes,
                        nonce_tta: bytes, key_size: int = 32) -> tuple[bytes, bytes]:
    """
    Derive bidirectional channel keys from Phase I KEM shared secret.

    K_cli→TTA ∥ K_TTA→cli = SHAKE-256(K_shared ∥ Nonce_cli ∥ Nonce_TTA)

    Two separate keys prevent reflection attacks (the original DLST-MQTT
    design requirement carried forward).

    Args:
        shared_secret: ML-KEM shared secret (32 bytes).
        nonce_client: Client's random nonce.
        nonce_tta: TTA's random nonce.
        key_size: Size of each derived key in bytes (default 32).

    Returns:
        (k_client_to_tta, k_tta_to_client): Two independent channel keys.
    """
    h = SHAKE256.new()
    h.update(shared_secret)
    h.update(nonce_client)
    h.update(nonce_tta)
    output = h.read(key_size * 2)
    return output[:key_size], output[key_size:]


def _prg(seed: bytes, length: int) -> bytes:
    """
    Pseudorandom Generator based on AES-256-CTR.

    PRG(seed) produces cryptographically independent output blocks,
    which is what Eq. 5 requires for single-point-of-compromise prevention.
    Each sub-topic at each epoch gets an independent key block.

    Args:
        seed: Input seed material (hashed to 32 bytes if not already).
        length: Number of output bytes.

    Returns:
        Pseudorandom output bytes.
    """
    # Derive a 32-byte AES key and 16-byte IV from the seed
    h = SHAKE256.new()
    h.update(seed)
    material = h.read(48)  # 32 bytes key + 16 bytes nonce
    aes_key = material[:32]
    aes_nonce = material[32:48]

    # AES-256-CTR as PRG — encrypt zeros to produce pseudorandom stream
    cipher = AES.new(aes_key, AES.MODE_CTR, nonce=aes_nonce[:8])
    return cipher.encrypt(b"\x00" * length)


def derive_subtopic_key(seed: bytes, epoch_id: int,
                        key_size: int = 32) -> bytes:
    """
    Derive a per-sub-topic symmetric key using PRG (Eq. 5).

    K_st_l = PRG(Seed_L ∥ EpochID)

    Uses AES-CTR as the PRG core to produce independent key blocks,
    preventing single-point-of-compromise across sub-topics/epochs.
    This is Option B from the protocol spec (lighter than fresh KEM
    encapsulation per topic; trades per-topic forward secrecy for performance).

    Args:
        seed: Per-security-level seed (generated by TTA).
        epoch_id: 16-bit epoch identifier.
        key_size: Size of derived key in bytes (default 32).

    Returns:
        Symmetric key for the sub-topic at this epoch.
    """
    prg_input = seed + struct.pack("!H", epoch_id)
    return _prg(prg_input, key_size)


def derive_salt(seed: bytes, epoch_id: int) -> bytes:
    """
    Derive a 6-byte (48-bit) epoch salt for IV construction.

    Salt_epoch is used in the data-plane IV:
        IV = Salt_epoch(48) ∥ ID_P(16) ∥ Counter32(32) = 96 bits = 12 bytes

    Args:
        seed: Salt derivation seed.
        epoch_id: 16-bit epoch identifier.

    Returns:
        6-byte salt.
    """
    prg_input = b"salt_derivation" + seed + struct.pack("!H", epoch_id)
    return _prg(prg_input, 6)


def derive_control_iv(direction_bit: int, sequence_number: int) -> bytes:
    """
    Construct a control-plane IV.

    IV_ctrl = b_dir(8) ∥ sn(32) ∥ 0^56 = 96 bits = 12 bytes

    The direction bit prevents IV reuse when both parties use
    the same sequence number space.

    Args:
        direction_bit: 0 for client→TTA, 1 for TTA→client.
        sequence_number: 32-bit sequence number.

    Returns:
        12-byte IV for control-plane AEAD.
    """
    # b_dir: 1 byte, sn: 4 bytes, padding: 7 bytes of zeros = 12 bytes total
    iv = struct.pack("!BI", direction_bit & 0xFF, sequence_number & 0xFFFFFFFF)
    iv += b"\x00" * 7  # pad to 12 bytes
    return iv


def derive_data_iv(salt_epoch: bytes, publisher_id: int,
                   counter: int) -> bytes:
    """
    Construct a data-plane IV.

    IV = Salt_epoch(48) ∥ ID_P(16) ∥ Counter32(32) = 96 bits = 12 bytes

    Args:
        salt_epoch: 6-byte (48-bit) epoch salt.
        publisher_id: 16-bit publisher identifier.
        counter: 32-bit message counter.

    Returns:
        12-byte IV for data-plane AEAD.
    """
    if len(salt_epoch) != 6:
        raise ValueError(f"Salt must be 6 bytes, got {len(salt_epoch)}")
    iv = salt_epoch + struct.pack("!HI", publisher_id & 0xFFFF, counter & 0xFFFFFFFF)
    return iv
